const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{токиофон1: 0},
	{играть: 0},
	{название: 0},
	{кумамното: 0},
	{лес: 0},
	{киото: 0},
	{Твёрдый: 0},
	{платформа: 0},
	{тыпроигра: 0},
	{назад: 0},
	{тывыиграл: 0},
	{мива: 0},
	{клетка: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{годжо: 0},
	{инструкция: 0},
	{Синусоида: 0},
	{дзего: 0},
	{дагон: 0},
	{"8Направлений": 0},
	{ханами: 0},
	{махито: 0},
	{небо: 0},
	{энергия: 0},
	{Пуля: 0},
	{красный: 0},
	{тодо: 0},
	{простотекст: 0},
	{обратно: 0},
	{кендзяку: 0},
	{пурпурный: 0},
	{проклятия: 0},
	{Мышь: 0},
	{тодо2: 0}
];

self.InstanceType = {
	токиофон1: class extends self.ITiledBackgroundInstance {},
	играть: class extends self.IButtonInstance {},
	название: class extends self.ITextInstance {},
	кумамното: class extends self.ITiledBackgroundInstance {},
	лес: class extends self.ITiledBackgroundInstance {},
	киото: class extends self.ITiledBackgroundInstance {},
	платформа: class extends self.ISpriteInstance {},
	тыпроигра: class extends self.ITextInstance {},
	назад: class extends self.IButtonInstance {},
	тывыиграл: class extends self.ITextInstance {},
	мива: class extends self.ISpriteInstance {},
	клетка: class extends self.ISpriteInstance {},
	годжо: class extends self.ISpriteInstance {},
	инструкция: class extends self.ITextInstance {},
	дзего: class extends self.ISpriteInstance {},
	дагон: class extends self.ISpriteInstance {},
	ханами: class extends self.ISpriteInstance {},
	махито: class extends self.ISpriteInstance {},
	небо: class extends self.ISpriteInstance {},
	энергия: class extends self.ISpriteInstance {},
	красный: class extends self.ISpriteInstance {},
	тодо: class extends self.ISpriteInstance {},
	простотекст: class extends self.ITextInstance {},
	обратно: class extends self.ITextInstance {},
	кендзяку: class extends self.ISpriteInstance {},
	пурпурный: class extends self.ISpriteInstance {},
	проклятия: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	тодо2: class extends self.ISpriteInstance {}
}